[build]
  command = "npm run site"
  publish = "dist"


# Optional: cache built assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
