[build]
  command = "npm run site"
  publish = "dist"

# Root path should redirect to the demo app
[[redirects]]
  from = "/"
  to = "/demo/"
  status = 301
  force = true

# Optional: cache built assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
